# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Elizabeth Ramos
email: elizabethlopesramos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elizabethramos.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: elizaramosv
github_username:  ElizabethRamos
facebook_username: elizaclr
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_username: elizabeth-ramos

# Build settings
markdown: kramdown
